name: formatter-lua

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled ]

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'format') }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            **/*.lua
            !**/*.yml
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Install stylua
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          wget https://github.com/JohnnyMorganz/StyLua/releases/download/v0.18.0/stylua-linux-x86_64.zip
          unzip stylua-linux-x86_64.zip
          chmod +x stylua
      - name: Format changed files with StyLua
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
            ./stylua ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Update repo before push
        run: |
          git pull
      - name: Commit changes and push current branch
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: ESX GITHUB ACTIONS BOT
          commit_user_email: esx-github-actions-bot@users.noreply.github.com
          commit_message: :art:Code formatted in *.lua files
          file_pattern: '*.lua'
          status_options: '--untracked-files=no'
